### PR TITLE
Fixed The Ui for the chat

### LINKED ISSUE #314: Improve Chat UI
- Padding handling
- Text Input problem
- Add name of sender
- Icons

### PR DESCRIPTION
**Pull request by Zep3k**
Screenshot_20240512-162606_SkySync
Screenshot_20240512-162544_SkySync
Screenshot_20240512-162541_SkySync
Close #314

### CODE REVIEW

File: app/src/main/java/ch/epfl/skysync/components/ChatText.kt [hunk 1]
```diff
@@ -118,35 +116,30 @@ fun ChatBubble(message: ChatMessage, index: String) {
...
-          } else {
-            Box(
-                modifier =
-                    Modifier.fillMaxWidth(0.075f)
-                        .size(30.dp)
-                        .background(color = Color.LightGray, shape = CircleShape)) {}
+        Column {
+          if (!isMyMessage) {
+            Text(
+                text = "${message.message.user.firstname} " + message.message.user.lastname,
```
Comment (Plouc314) [inline app/src/main/java/ch/epfl/skysync/components/ChatText.kt:122]: Here you can use `message.message.user.name()`

File: app/src/main/java/ch/epfl/skysync/components/ChatText.kt [hunk 2]
```diff
@@ -97,7 +96,6 @@ fun ChatTextBody(messages: List<ChatMessage>) {
 @Composable
 fun ChatBubble(message: ChatMessage, index: String) {
   var isMyMessage = false
```
Comment (mathieumognol) [inline app/src/main/java/ch/epfl/skysync/components/ChatText.kt:98]: Could be simplified by using a single expression: ```val isMyMessage = message.messageType == MessageType.SENT```

File: app/src/main/java/ch/epfl/skysync/components/ChatText.kt [hunk 3]
```diff
@@ -38,6 +36,7 @@ import androidx.compose.ui.Modifier
 import androidx.compose.ui.graphics.Color
 import androidx.compose.ui.platform.LocalSoftwareKeyboardController
 import androidx.compose.ui.platform.testTag
+import androidx.compose.ui.text.TextStyle
 import androidx.compose.ui.text.input.ImeAction
 import androidx.compose.ui.unit.dp
 import androidx.compose.ui.unit.sp
```
Comment (mathieumognol) [inline app/src/main/java/ch/epfl/skysync/components/ChatText.kt:42]: I can't add comment to line 84 because it is old code but: The `LaunchedEffect` should use `messages` as a key to ensure the list scrolls to the latest message whenever `messages` change. Ex: ```LaunchedEffect(messages) {
        if (messages.isNotEmpty()) {
            lazyListState.scrollToItem(messages.size - 1)
        }
    }```

**Review by mathieumognol — APPROVED** [review]
LGTM
