### PR TITLE
Fix available equipement

### LINKED ISSUE #340: Fix flight viewmodel
* When modifying the date of a flight the selected user should not be selected if not available on this new date
* Filter available user according to their role

### PR DESCRIPTION
**Pull request by Prolas**
## Bug
When modifying a flight, one could select a new date, and confirm even if the team, balloon or basket are not available.

## Solutions
On date or timeslot changes, check if the user/equipment are available. If not display an error on the field.

## UX enhancement
Addition of deletion button for balloon and basket to unset a balloon or basket.

close #340

### CODE REVIEW

File: app/src/main/java/ch/epfl/skysync/screens/admin/ModifyFlight.kt [hunk 1]
```diff
@@ -16,18 +16,25 @@ fun ModifyFlightScreen(
...
+  val allBalloons = viewModel.currentBalloons.collectAsStateWithLifecycle()
+  val allBaskets = viewModel.currentBaskets.collectAsStateWithLifecycle()
+  val allVehicles = viewModel.currentVehicles.collectAsStateWithLifecycle()
+  val availableUsers = viewModel.availableUsers.collectAsStateWithLifecycle()
   val allRoleTypes = RoleType.entries
+
+  if (flightToModify.value != null) {
+    viewModel.setFlight(flightToModify.value!!)
+    println(flightToModify)
+    println(allBaskets)
```
Comment (Plouc314) [inline app/src/main/java/ch/epfl/skysync/screens/admin/ModifyFlight.kt:30]: Leftover prints

File: app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt [hunk 2]
```diff
@@ -133,12 +139,18 @@ class FlightsViewModel(
                   localDate = date!!,
                   timeslot = timeSlot!!,
                   onError = { onError(it) })
+
+          if (_flight.value?.balloon != null && firstFill) {
```
Comment (Plouc314) [inline app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt:143]: Instead of checking if it is the first time it is refreshed, you should check if the date is the date of the flight, that way you can add the flight members as available users when the date match and not otherwise

File: app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt [hunk 3]
```diff
@@ -133,12 +139,18 @@ class FlightsViewModel(
...
+            val availableBalloons = _availableBalloons.value.filter { it != _flight.value?.balloon }
+            _availableBalloons.value = availableBalloons.plus(_flight.value?.balloon!!)
+            println(_availableBalloons.value)
```
Comment (Plouc314) [inline app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt:146]: Leftover print

File: app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt [hunk 4]
```diff
@@ -147,26 +159,38 @@ class FlightsViewModel(
...
+          }
         } else {
           _availableUsers.value = repository.userTable.getAll(onError = { onError(it) })
         }
       }
 
-  fun refreshAvailableVehicles() =
+  fun refreshAvailableVehicles(firstFill: Boolean = false) =
       viewModelScope.launch {
+        println("REFRESH VEHICLES")
```
Comment (Plouc314) [inline app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt:174]: Leftover print but in upper case

Comment (Prolas) [reply app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt:174]: I will change it

File: app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt (hunk 2 above)
Comment (Prolas) [reply app/src/main/java/ch/epfl/skysync/viewmodel/FlightsViewModel.kt:143]: Good catch. I will change it

**Review by Plouc314 — APPROVED** [review]
LGTM
